Add a new snippet
roerohan/vscode-MongoSnippets-NodeJS pull request #28
Opened 2021-10-31 16:52 UTC by AsianCat54x

* **Please check if the PR fulfills these requirements**
- [X] The commit message follows our guidelines
- [X] Tests for the changes have been added (for bug fixes / features)

This pull request added a snippet for connecting to the mongo cloud server.

* **What is the current behavior?** (You can also link to an open issue here)

For issue #10

2021-11-11 19:50 UTC, roerohan requested changes

2021-11-11 19:50 UTC, roerohan commented on src/snippets/snippets.json
> +        "prefix": "!mdbcc",
The prefix `!mdbcc` is already in use

2021-11-11 19:50 UTC, roerohan commented on src/snippets/snippets.json
> +            "// Connect MongoDB at default port 27017.",
Comment is invalid

2021-11-11 19:50 UTC, roerohan commented on src/snippets/snippets.json
> +            "mongoose.connect('mongodb+srv://${1:Username}:${2:Password}@${3:Database Name In Lowercase}.osusz.mongodb.net/${Database Name}?retryWrites=true&w=majority', {",
Do you think it would be a better idea to just accept the entire mongo connection URL in `!mdbc` instead of adding a new command just to connect to cloud? E.G

```ts
mongoose.connect('${1:DB URL}', {...});
```

2021-11-12 02:02 UTC, AsianCat54x commented on src/snippets/snippets.json
> +            "mongoose.connect('mongodb+srv://${1:Username}:${2:Password}@${3:Database Name In Lowercase}.osusz.mongodb.net/${Database Name}?retryWrites=true&w=majority', {",
You can do it like this, but MongoDB gives the same link as I did. It does not provide the whole link, you have to fill in some details. If you want then I can do it like this (as you have requested)

2021-11-12 06:03 UTC, roerohan commented on src/snippets/snippets.json
> +            "mongoose.connect('mongodb+srv://${1:Username}:${2:Password}@${3:Database Name In Lowercase}.osusz.mongodb.net/${Database Name}?retryWrites=true&w=majority', {",
Alright makes sense then, let's keep it this way. You would still need to change the abbreviation though. Check https://github.com/roerohan/vscode-MongoSnippets-NodeJS/pull/28#discussion_r747774147

2021-11-16 07:14 UTC, roerohan approved these changes

2021-11-16 07:15 UTC, merged

2021-11-16 07:15 UTC, roerohan commented
Looks good to me, thanks @AsianCat54x

2021-11-16 09:40 UTC, AsianCat54x commented
Your's Welcome :D